<a href="https://colab.research.google.com/github/avii-001/Numpy/blob/main/Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Numpy Exercises
# Multiply the following two NumPy arrays element-wise: [1, 2, 3] and [4, 5, 6], and print the result.
array1=np.array([1, 2, 3])
array2=np.array([4, 5, 6])
mul_arr=array1*array2
mul_arr

array([ 4, 10, 18])

In [ ]:
# Calculate the mean of the following NumPy array: [3, 7, 10, 15, 19], and print the result.
arr3=np.array([3, 7, 10, 15, 19])
print(f'Mean of {arr3} ={np.mean(arr3)}')

Mean of [ 3  7 10 15 19] =10.8


In [ ]:
# Reshape the following NumPy array into a 2x3 matrix: [1, 2, 3, 4, 5, 6].
arr=np.array([1, 2, 3, 4, 5, 6])
arr.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Find the maximum value in the following NumPy array: [9, 2, 7, 5, 3], and print it.
arr=np.array([9, 2, 7, 5, 3])
print(f'Max value in {arr} is {np.max(arr)}')

Max value in [9 2 7 5 3] is 9


In [ ]:
# More exercises

# Create a 2D NumPy array with shape (5, 5) containing random integers between 1 and 100.
arr5=np.random.randint(1,100,(5,5))
arr5

array([[92, 46, 41, 54, 73],
       [ 4, 27, 14, 94, 66],
       [35, 41, 32, 28,  6],
       [45,  6, 64, 12, 71],
       [95, 25, 96, 91,  4]])

In [ ]:
# Replace all values greater than 50 with 0 and print the modified array.
arr5[arr5>50]=0
arr5

array([[ 0, 46, 41,  0,  0],
       [ 4, 27, 14,  0,  0],
       [35, 41, 32, 28,  6],
       [45,  6,  0, 12,  0],
       [ 0, 25,  0,  0,  4]])

In [ ]:
# Create a 1D NumPy array with 20 elements ranging from 0 to 100. Reshape the array into a 4x5 matrix and print it.
arr6=np.random.randint(1,100,(1,20))
print(f'New random array\n{arr6}')
arr7=arr6.reshape((4,5))
print(f'\nReshaped array\n{arr7}')

New random array
[[75 25 32 89 15 23 50 62 54 54 54  3 91 37 27 41 39 76 17 66]]

Reshaped array
[[75 25 32 89 15]
 [23 50 62 54 54]
 [54  3 91 37 27]
 [41 39 76 17 66]]


In [ ]:
# Create a 3x3 matrix with random values between 0 and 1. Replace all values less than 0.5 with 0 and print the modified matrix.
arr8=np.random.random((3,3))

In [ ]:
arr8[arr8<0.5]=0
arr8

array([[0.        , 0.        , 0.        ],
       [0.78613223, 0.8381241 , 0.92922875],
       [0.        , 0.        , 0.51910651]])

In [ ]:
# Create a 1D NumPy array with 100 elements ranging from 1 to 100. Reshape the array into a 10x10 matrix and calculate the sum of each row.
# Print the sum.
arr9=np.random.randint(1,101,(1,100))
print(arr9)
print()
arr10=arr9.reshape((10,10))
print(arr10)
print(f'\nSum of each row: {arr10.sum(axis=1)}')

[[41 40 23 25 52 87 62 48 57 70 57 93  1 63 63 46 22 12  4 63 72 82 13 65
  79 15 30 77 96  4 73 99 39 15 26 22 35 77 91 52 21 22 89 63 82 87 28 41
  83 44 11 73 61 14 13 89 84 41 84 10 54 57 59 10 48 54 65 54 32 16 16 59
  31 49 60 59 56 50 44 84 49 53 56  9  2 54 35 86 59 41 42 64 21 26 61  1
  14 54 99 35]]

[[41 40 23 25 52 87 62 48 57 70]
 [57 93  1 63 63 46 22 12  4 63]
 [72 82 13 65 79 15 30 77 96  4]
 [73 99 39 15 26 22 35 77 91 52]
 [21 22 89 63 82 87 28 41 83 44]
 [11 73 61 14 13 89 84 41 84 10]
 [54 57 59 10 48 54 65 54 32 16]
 [16 59 31 49 60 59 56 50 44 84]
 [49 53 56  9  2 54 35 86 59 41]
 [42 64 21 26 61  1 14 54 99 35]]

Sum of each row: [505 424 533 529 560 480 449 508 444 417]


In [ ]:
# Create a 2D NumPy array with shape (4, 4) containing random integers between 1 and 10. Find the indices of the maximum value in each row and
# print the indices.
arr11=np.random.randint(1,11,(4,4))
print(arr11)

print('\nMaximum of each row')
print(arr11.max(axis=1))

print('\nIndices of maximum of each row')
print(arr11.argmax(axis=1))

[[ 8  3  9  6]
 [ 7  7 10  9]
 [10  9  2  3]
 [ 2  9  7 10]]

Maximum of each row
[ 9 10 10 10]

Indices of maximum of each row
[2 2 0 3]


In [ ]:
# Create a 1D NumPy array with 50 random elements randomly. Calculate the mean and standard deviation of the array and print the results.
arr12=np.random.randint(1,100,(1,50))
print(arr12)
print(f'Mean: {arr12.mean()}')
print(f'Standard Deviation: {arr12.std():.2f}')

[[64 21 81 88 51 48 53 48 57 29 62 86 15 23 30 90 13 79 44 21 76 30 73  9
  17 95 50 47 11 23 66 39 14 88 82 81 59 53 88 91 63 60 68  1 58 13 24 12
  89 63]]
Mean: 50.92
Standard Deviation: 27.42


In [ ]:
# Create a 2D NumPy array with shape (3, 3) and fill it with values ranging from 0 to 8. Shuffle the rows randomly and
# print the shuffled array.
arr13=np.random.randint(0,8,(3,3))
print(arr13)

[[5 4 4]
 [6 0 4]
 [2 7 0]]


In [ ]:
np.random.shuffle(arr13)
print(arr13)

[[2 7 0]
 [6 0 4]
 [5 4 4]]


In [ ]:
# Create a 1D NumPy array with 100 elements ranging from 1 to 10. Replace all odd values with -1 and print the modified array.
arr14=np.random.randint(1,11,100)
arr14

array([ 2,  4, 10,  5,  6,  8,  9,  3,  3, 10,  8,  3,  5, 10,  1,  2, 10,
        2,  9,  6,  8,  1,  9,  8,  5,  4,  3,  5,  3,  4,  4,  8,  5,  6,
        7,  2,  3,  6, 10,  2,  2,  9,  2,  3,  2,  4,  6,  8,  1,  1,  4,
        5,  8,  1,  8,  3,  7, 10,  6,  6,  3,  7,  7,  3,  9,  6,  2,  3,
        5,  7,  1,  3,  7,  2, 10,  5,  5,  5,  3,  6,  9,  1,  3,  6,  7,
        1,  1,  4,  4,  3,  4,  9,  5,  8,  2,  1,  8,  8,  5,  7])

In [ ]:
arr14[arr14%2==1]=-1
arr14

array([ 2,  4, 10, -1,  6,  8, -1, -1, -1, 10,  8, -1, -1, 10, -1,  2, 10,
        2, -1,  6,  8, -1, -1,  8, -1,  4, -1, -1, -1,  4,  4,  8, -1,  6,
       -1,  2, -1,  6, 10,  2,  2, -1,  2, -1,  2,  4,  6,  8, -1, -1,  4,
       -1,  8, -1,  8, -1, -1, 10,  6,  6, -1, -1, -1, -1, -1,  6,  2, -1,
       -1, -1, -1, -1, -1,  2, 10, -1, -1, -1, -1,  6, -1, -1, -1,  6, -1,
       -1, -1,  4,  4, -1,  4, -1, -1,  8,  2, -1,  8,  8, -1, -1])

In [ ]:
# Create a 3x3 matrix with random values between 0 and 1. Normalize the matrix by dividing each row by the sum of its elements and
# print the normalized matrix.
arr15=np.random.random((3,3))
arr15

array([[0.17934646, 0.79082143, 0.30591171],
       [0.46403941, 0.00512039, 0.98420146],
       [0.67803916, 0.37797785, 0.00640726]])

In [ ]:
norm=arr15.sum(axis=1)
norm

array([1.2760796 , 1.45336126, 1.06242427])

In [ ]:
div=np.divide(arr15,norm)
div

array([[0.14054488, 0.54413273, 0.28793742],
       [0.36364456, 0.00352314, 0.92637328],
       [0.5313455 , 0.26007151, 0.0060308 ]])

In [ ]:
# Create a 2D NumPy array with shape (5, 5) and fill it with random values between 0 and 1. Sort the elements in each column in descending order
#  and print the sorted array.


In [ ]:
arr16=np.random.random((5,5))
arr16

array([[0.90127832, 0.01394339, 0.47696783, 0.05424043, 0.2095671 ],
       [0.61360943, 0.10585712, 0.37072986, 0.80619858, 0.14611452],
       [0.22353447, 0.17930188, 0.47560751, 0.06119202, 0.71019273],
       [0.36757011, 0.94464287, 0.23261438, 0.34150927, 0.09998277],
       [0.14800066, 0.26648492, 0.92799387, 0.31864275, 0.60777638]])

In [ ]:
arr16.sort(axis=0)
arr16[::-1]

array([[0.90127832, 0.94464287, 0.92799387, 0.80619858, 0.71019273],
       [0.61360943, 0.26648492, 0.47696783, 0.34150927, 0.60777638],
       [0.36757011, 0.17930188, 0.47560751, 0.31864275, 0.2095671 ],
       [0.22353447, 0.10585712, 0.37072986, 0.06119202, 0.14611452],
       [0.14800066, 0.01394339, 0.23261438, 0.05424043, 0.09998277]])