<a href="https://colab.research.google.com/github/avii-001/Numpy/blob/main/Squid_game_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Squid Game NumPy Challenges - Questions
# 1. Red Light, Green Light
# Create a 1D NumPy array of 10 random integers between 1 and 100, representing players' distances.
# Identify which players stopped when the distance is less than or equal to 50. Print the results.

# 2. Honeycomb Challenge
# Create a 4x4 NumPy array with random integers between 1 and 9.
# Extract and print a specific shape (e.g., a cross or L-shape) from the array using slicing.

# 3. Tug of War
# Create two 1D NumPy arrays of 5 random integers each, representing two teams' strengths.
# Calculate the total strength of each team.
# Determine and print which team wins or if it’s a tie.

# 4. Marble Game
# Create a 1D NumPy array with 10 random integers between -5 and 5, representing marbles won (+) or lost (-) by players.
# Calculate the total marbles at the end and print the result.

# 5. Glass Bridge
# Create a 1D NumPy array of size 10 with random 0s (broken) and 1s (safe), representing the glass bridge.
# Simulate 10 random steps through the bridge.
# Check and print if the player survives (steps land only on 1s) or falls (steps land on 0s).


In [ ]:
# Squid Game NumPy Challenges - Questions
# 1. Red Light, Green Light
# Create a 1D NumPy array of 10 random integers between 1 and 100, representing players' distances.
# Identify which players stopped when the distance is less than or equal to 50. Print the results.

red_green_light=np.random.randint(1,101,(1,10))
print('Players')
print(red_green_light)
print('\nPlayers who stopped before or at 50')
red_green_light<=50

Players
[[43 64 87 86 42 22 85 34 94 77]]

Players who stopped before or at 50


array([[ True, False, False, False,  True,  True, False,  True, False,
        False]])

In [ ]:
# 2. Honeycomb Challenge
# Create a 4x4 NumPy array with random integers between 1 and 9.
# Extract and print a specific shape (e.g., a cross or L-shape) from the array using slicing.
honey_comb=np.random.randint(1,10,(4,4))
print(honey_comb)
honey_comb[:,1:3]

[[3 6 6 2]
 [7 9 2 3]
 [8 6 8 7]
 [2 1 6 3]]


array([[6, 6],
       [9, 2],
       [6, 8],
       [1, 6]])

In [ ]:
# 3. Tug of War
# Create two 1D NumPy arrays of 5 random integers each, representing two teams' strengths.
# Calculate the total strength of each team.
# Determine and print which team wins or if it’s a tie.

team1=np.random.randint(1,10,(1,6))
team2=np.random.randint(1,10,(1,6))
print(team1,team2)

[[9 8 4 1 8 4]] [[8 1 9 3 9 3]]


In [ ]:
team1_strength=np.sum(team1)
team2_strength=np.sum(team2)
print(f'team1_strength:{team1_strength}')
print(f'team2_strength:{team2_strength}')

team1_strength:34
team2_strength:33


In [ ]:
result='Its a Tie' if team1_strength==team2_strength else ('Winner is Team 1 ' if team1_strength>team2_strength else 'Winner is Team 2')
result

'Winner is Team 1 '

In [ ]:
# 4. Marble Game
# Create a 1D NumPy array with 10 random integers between -5 and 5, representing marbles won (+) or lost (-) by players.
# Calculate the total marbles at the end and print the result.

marbles=np.random.randint(-5,6,(1,10))
print(marbles)

[[-3  2  3  0 -4 -5 -4 -3  0 -2]]


In [ ]:
marble_sum=np.sum(marbles)
print(f'Total marbles: {marble_sum}')

Total marbles: -16


In [ ]:
# 5. Glass Bridge
# Create a 1D NumPy array of size 10 with random 0s (broken) and 1s (safe), representing the glass bridge.
# Simulate 10 random steps through the bridge.
# Check and print if the player survives (steps land only on 1s) or falls (steps land on 0s).

glass_bridge=np.random.choice([0,1], size=10)
print(glass_bridge)

steps=np.random.choice([0,1], size=10)
print(steps)

[0 0 0 0 1 1 1 0 1 0]
[1 1 1 0 0 0 1 0 0 1]


In [ ]:
if np.all(glass_bridge[steps==1]==1):
  print('Survived')
else:
  print('Fell')

Fell
